// RecentTransactionCard
// AdminRecentTransactionsCard
// IndividualTransactionsCard
// BuyerTransactCard
// SellerTransactCard
// TransactionCompletedCard
// TransactionSummary
// EscrowInitiationsTerms&ConditionCard
// TransactionsAgreedCard
// PaymentMadeCard
// PaymentGatewayCard
// TransactionCompletionCard
// InitiateTransactionsCard
// SettledTransactionsCards
